$('[data-fancybox="gallery"]').fancybox({
    animationDuration: 366,
    animationEffect: "zoom",
    baseTpl: '<div class="fancybox-container" role="dialog" tabindex="-1"><div class="fancybox-bg"></div><div class="fancybox-inner"><div class="fancybox-infobar"><span data-fancybox-index></span>&nbsp;/&nbsp;<span data-fancybox-count></span></div><div class="fancybox-toolbar">{{buttons}}</div><div class="fancybox-navigation">{{arrows}}</div><div class="fancybox-stage"></div><div class="fancybox-caption"><div class="fancybox-caption__body"></div></div></div></div>',
    buttons: ["slideShow", "zoom", "thumbs", "download", "close"],
    clickOutside: "close",
    clickSlide: "close",
    closeExisting: false,
    dblclickContent: false,
    dblclickOutside: false,
    dblclickSlide: false,
    defaultType: "image",
    fullScreen: {autoStart: false},
    gutter: 50,
    hash: null,
    hideScrollbar: true,
    idleTime: 3,
    image: {preload: false},
    slideShow: {autoStart: false, speed: 3000, progress: true},
    smallBtn: "auto",
    spinnerTpl: '<div class="fancybox-loading"></div>',
    thumbs: {autoStart: true, hideOnClose: true, parentEl: ".fancybox-container", axis: "y"},
    toolbar: "auto",
    touch: {vertical: true, momentum: true},
    transitionDuration: 366,
    transitionEffect: "fade",
    trapFocus: true
});